# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15GFi6tj8d0rRTniPoC_BmW5Rgf5jhXTO
"""

import pandas as pd
df = pd.DataFrame({ 'Familiya' : [ 'Tursunov','Eshboyev',"Yo'ldashev",'Muhammadaliyev','Mamatvaliyev','Abduxakimov','Azizibloyev',"Do'ltaboyev",'Komilova','Madaminjonov','Mamadaliyev' ,'Mirzahamidov',"Ne'matova",'Nurmuhammadov'     ],

                    'Ism' : [  'Muhammadqodir' ,'Ilhom', 'Husniddin','Abdullo','Dilshodbek','Xursandbek','Hojiakbar','Muhammadjon','Dinora','Baxtiyorjon','Zikrullo','Jaloliddin','Dildoraxon','Muhammad' ],

                    'Yoshi' : [   '19' ,'19','19','19','19','19','19','19','19','19','19','19','19','19'],
                    'Kursi' : [     '2' ,'2' ,'2','2','2','2','2','2','2','2','2','2','2','2']

})
print(df)

df.to_excel('malumot.xlsx', index=False, sheet_name='Sheet1' )